### ISSUE TITLE
please bundle for webpack

### ISSUE THREAD

**Issue by samvloeberghs** [fulls1z3/ngx-meta#1]

**Comment by fulls1z3** [comment]
Hi Sam, I'm a bit new to webpack. However, I'll investigate this and try to provide a bundle for webpack in the next release. Meantime, I'll be open to any kind of co-operation.

Thanks!

**Comment by fulls1z3** [comment]
Hi, are we talking about the following issue?

```
WARNING in ./~/ng2-metadata/dist/bundles/ng2-metadata.umd.min.js
Critical dependencies:
1:4508-4515 require function is used in a way in which dependencies cannot be statically extracted
1:4560-4567 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/ng2-metadata/dist/bundles/ng2-metadata.umd.min.js 1:4508-4515 1:4560-4567
```

**Comment by samvloeberghs** [comment]
@fulls1z3 no, just checkout other repo's like ng2-translate and how they are delivering their package :)
thanks for your effort. Please keep in mind that this package as for now is useless.. Unless you run it on the server. No time to elaborate on it now, but look into Universal, you'll get it!

**Comment by fulls1z3** [comment]
Hi Sam, thanks for your comments. Despite I was new to webpack (fortunately now not), I am sharing the same thoughts, that the package is useless unless it successfully compiles on AoT and bundled with webpack.

Today, I was looking at the same repo (ng2-translate) as well as others (ng2-bootstrap, etc.) and I'm about to deliver the package in the same way as ng2-translate does (webpack bundle).

Please keep in mind that ng2-bootstrap is also about to deliver webpack bundles. If you clone the dev. branch (or use relevant bundled files), you'll be able to compile those components in webpack.

On the other hand, you can give a try with the attached file ([ng2-metadata.umd.min.js.zip](https://github.com/fulls1z3/ng2-metadata/files/603800/ng2-metadata.umd.min.js.zip)).

**Comment by samvloeberghs** [comment]
@fulls1z3 it has nothing to do with aot, it's just that metadata is only usefull / indexable by all search engines / social providers if the HTML is rendered on the server. This will only work for Google's search engine, that is able to crawl heavy javascript applications.

**Comment by fulls1z3** [comment]
@samvloeberghs thanks again for your comments. I'm aware that the metadata generated by this package is "dynamic" - cannot be indexed any search engines except Google, and also it's not introduced as a replacement of server-side solution to render meta tags.

Furthermore, for a complete SEO, other page elements (as well as page contents) should be rendered on the server as well (yeah - angular universal, or prerender.io, phantomjs, etc..).

However, this topic refers to webpack bundling of the repo, so I'm closing the issue as it goes off-topic.

**Comment by fulls1z3** [comment]
Hi @sambloeverghs, as of v0.2.0-rc.5 it supports server-side rendering. Hope you're still interested in `@nglibs/meta` :smile:

**Comment by samvloeberghs** [comment]
Good job!😎
