### ISSUE TITLE
doesnt seem to work with lazy load routes e.g. loaded Children

### ISSUE THREAD

**Issue by markoddi01** [fulls1z3/ngx-meta#10]
Doesnt seem to work with lazy load routes e.g. loaded Children.

Eg:
{path: 'createJob', loadChildren: 'app/components/createJob/createJob.module#CreateJobModule'},

Google still picks up the homepage only.

**Comment by fulls1z3** [comment]
Hi @markoddi01,

Can you please give more details about your problem?
