### ISSUE TITLE
view page source

### ISSUE THREAD

**Issue by jcdsr** [fulls1z3/ngx-meta#11]
If I check a page as "View page source" the title is the original from the main index.html and the description is empty. However, if I inspect the page, the title and the description will load the data as in the component in the inspector. However, I'm not sure after the page is crawled will read the correct title and description, because seems injected instead of rendered. 

Is there a solution for this?

I'm using the structure of quickstart tutorial from angular 2 - Mac mini - osx sierra. - Chrome v55

**Comment by fulls1z3** [comment]
Hi @carlosdv4 

Thanks for your interest in `ng2-metadata`.

As mentioned in #4:

> Generated metadata is not **currently** accessible by bots except Google crawler. For now, the only method to generate meta tags at the server-side in order to be crawl-able by bots such as facebook.
> 
> However, I'm keeping track of developments with those crawlers/bots and will publish updates as things become available.

And in #5:

> `ng2-metadata` does not change source, it manipulates the head elements during runtime. I think that's the reason why you're not seeing changes in the source but in the developer console - so that I can say that's the expected behavior.

Please check the README and search github for a similar issue or PR before submitting.
