### ISSUE TITLE
cannot read property 'Injectable' of undefined

### ISSUE THREAD

**Issue by A50** [fulls1z3/ngx-meta#12]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => check the README and search github for a similar issue or PR before submitting
[ x ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.4

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.1.5]

* **Node (for AoT issues):** `node --version` =   7.2.1

When start my app, in console next error

> Uncaught TypeError: Cannot read property 'Injectable' of undefined
>     at eval (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:6388)
>     at Object.t.AppendPageTitle (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:6506)
>     at e (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:897)
>     at Object.eval (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:6967)
>     at e (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:897)
>     at eval (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:1281)
>     at eval (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:1290)
>     at eval (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:633)
>     at eval (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:765)
>     at eval (<anonymous>)

How to fix this error? Thank's

**Comment by fulls1z3** [comment]
Hi @A50, thanks for your interest on `ng2-metadata`.

First of all, I'd like to say that there's too little information regarding to the problem you've faced. Based on the information you provided, I can say that `ng2-metadata` is tested on TypeScript 2.0.10, and it's known that angular has issues on a higher version of TypeScript than 2.0.10.

But I don't think it can cause this problem. It would be useful that you make a check of imports at the code file you're having this issue. For instance, it's known that with the latest angular/rxjs updates, many people suffered from versions mismatch (rxjs). Even I had to use `import 'map' from 'rxjs';` to be able to use the map function.

These are just rough assumptions. If you'll be able to provide more detailed information regarding your source code, I'll try to assist you to find and solve this problem.

**Comment by A50** [comment]
It is possible that there are problems with the import / export module
> t.AppendPageTitle	@	VM1248:formatted:241
piece of code:
```
`  t.prototype.updateMetadata = function(t, e) {
        var a = this;
        t.disabled || (this.setTitle(t.title, t.override),
        Object.keys(t).forEach(function(e) {
          var r = t[e];
          if ("title" !== e && "override" !== e) {
            if ("og:locale" === e)
              r = r.replace(/-/g, "_");
            else if ("og:locale:alternate" === e) {
              var i = t["og:locale"];
              return void a.updateLocales(i, t[e])
            }
            a.setTag(e, r)
          }
        }),
        this.metadataSettings.defaults && Object.keys(this.metadataSettings.defaults).forEach(function(e) {
          var r = a.metadataSettings.defaults[e];
          if (!(e in a.isMetadataSet || e in t || "title" === e || "override" === e)) {
            if ("og:locale" === e)
              r = r.replace(/-/g, "_");
            else if ("og:locale:alternate" === e) {
              var i = t["og:locale"];
              return void a.updateLocales(i, a.metadataSettings.defaults[e])
            }
            a.setTag(e, r)
          }
        }),
        this.setTag("og:url", (this.metadataSettings.applicationUrl || "/") + e.replace(/\/$/g, "")))
      }
      ,
      t = l([a.i(i.Injectable)(), d(1, a.i(i.Inject)(r.DOCUMENT)), c("design:paramtypes", [n.Router, Object, r.Title, n.ActivatedRoute, f])], t)
    }()
  }`
```

error on 241 ->
` t = l([a.i(i.Injectable)(), d(1, a.i(i.Inject)(r.DOCUMENT)), c("design:paramtypes", [n.Router, Object, r.Title, n.ActivatedRoute, f])], t)`


>   at Object.t.AppendPageTitle (eval at webpackJsonp.308.module.exports (addScript.js:9), <anonymous>:1:6506)
piece of code:
```
`module.exports = function(src) {
	if (typeof execScript !== "undefined")
		execScript(src);
	else
        // addScript.js:9 error 
  	  eval.call(null, src);
}`
```
