### ISSUE TITLE
meta data readable by Facebook/Twitter?

### ISSUE THREAD

**Issue by kodeine** [fulls1z3/ngx-meta#13]
Can facebook/twitter bots read meta data as of now with latest angular i see the [meta service introduced](https://github.com/angular/angular/pull/12322).

**Comment by fulls1z3** [comment]
Yeah I've also noticed that meta service has been introduced by Angular. However, it only contains a small subset of `ng2-metadata` utility.

About facebook/twitter bots, there's still no remarkable update.
