### ISSUE TITLE
no .js files after installing from npm's registry 

### ISSUE THREAD

**Issue by aegyed91** [fulls1z3/ngx-meta#16]
Hey again @fulls1z3, sorry i deleted the issue template 

so today i wanted to give another shot to the new meta lib (still using your old one 💃 ), but now i ran into another weird problem. 

Check this screenshot: http://imgur.com/a/i8Vcs

There is no `*.js` or `*.ts` file under `./node_modules/@nglibs/meta` . Something fishy must be going on in the `.npmignore` or in the build process.

the latest published version on npm's registry atm is `0.2.0-rc.2`

**Comment by fulls1z3** [comment]
Hi @tsm91, gonna fix that as a first thing in the morning with 0.2.0-rc.3, and sorry for the inconvience :(

**Comment by aegyed91** [comment]
np, will try again next time :D

**Comment by fulls1z3** [comment]
@nglibs/meta v0.2.0-rc.3 has been published, you can enjoy it ;)

**Comment by fulls1z3** [comment]
Meanwhile, you can have a look at the [example-app](https://github.com/nglibs/example-app), demonstrating use of all @nglibs utils.
