### ISSUE TITLE
server-side rendering (universal) compability

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/ngx-meta#20]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```

**Current behavior**
Nor by viewing the page source, neither by sharing the page on facebook/twitter/etc, the dynamically generated meta tags by @nglibs/meta are revealed. These meta tags can only be viewed using developer tools on the browser.

**Expected/desired behavior**
Dynamically generated meta tags should be visible on the page source, as well as they should be readable by sharing the page on web/social networks/etc. 

**Minimal reproduction of the problem with instructions**
- https://github.com/nglibs/meta/issues/14
- https://github.com/nglibs/meta/issues/13
- https://github.com/nglibs/meta/issues/11
- https://github.com/nglibs/meta/issues/9
- https://github.com/nglibs/meta/issues/5
- https://github.com/nglibs/meta/issues/4
- https://github.com/nglibs/meta/issues/1

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by empurium** [comment]
+1 on this! I'm working on getting this going with Angular Universal right now as well. Forked the ng-universal-demo repository. I'll let you know if I have any findings.

**Comment by fulls1z3** [comment]
Hi @empurium, actually @nglibs/meta currently works (as of [1ff82a2](https://github.com/nglibs/meta/commit/1ff82a2fcf4a8278f8951ab0932a1a44ad7543e8)) with Angular Universal. Also, I'm planning to add the meta functionality on [universal-example-app](https://github.com/nglibs/universal-example-app).

However, I'm working on triggering callbacks using a route guard (#35) so that the meta information passed to the service & on route definitions could be processed (ex: using ngx-translate). This way, meta tags processed by a callback function will be visible on HTML source.

Keep an eye on this repo, soon a great update will appear.
