### ISSUE TITLE
Angular v9 support

### ISSUE THREAD

**Issue by patrickmichalina** [fulls1z3/ngx-meta#204]

**Comment by fulls1z3** [comment]
agree! coming soon

**Comment by jtammen** [comment]
@fulls1z3 Are you aware of anything that does NOT work with Angular 9 at the moment?

**Comment by rafa-suagu** [comment]
@fulls1z3 do you accept PR about this?

**Comment by fulls1z3** [comment]
https://github.com/fulls1z3/ngx-meta/pull/207
