### ISSUE TITLE
@ngx-meta/core Doesn't support Angular 11.X.X

### ISSUE THREAD

**Issue by Heatmanofurioso** [fulls1z3/ngx-meta#210]
**I'm submitting a ...**
```
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
```

**Current behavior**
Currently we can't update Angular projects to 11.x.x using ng update, which also contain @ngx-meta/core due to @ngx-meta/core only supporting up until 10.0.0

**Expected/desired behavior**
@ngx-meta/core should be able to support Angular 11.x.x

**Minimal reproduction of the problem with instructions**
Any Angular project in 10.x.x, and attempting to perform **ng update  @angular/core**

**What is the motivation / use case for changing the behavior?**
Keeping up with current versions of Angular and keeping the package alive and relevant with current developments

**Environment**
* **Angular version:** 11.0.1

* **For Tooling issues:**
- Node version: 12.18.4
- Platform:  Windows 10 Professional Edition

**Comment by MaxKless** [comment]
I'm facing the same issue, any info on this?

**Comment by matusbielik** [comment]
@fulls1z3 is this library still developed?

**Comment by matusbielik** [comment]
@fulls1z3 asking again... Are there any plans to continue development or at least supporting this library for new Angular versions?
I was able to upgrade it to work for Ng10 locally, but because of actual permissions, I can't push the branch to remote to make PR, therefore it is not possible to follow contributions guidelines for this repo.

`
ngx-meta git:(ng-v10-upgrade) git push
remote: Permission to fulls1z3/ngx-meta.git denied to matusbielik.
fatal: unable to access 'https://github.com/fulls1z3/ngx-meta.git/': The requested URL returned error: 403
`


Can you please provide any statement on this? Or should we forsake this library for good?

**Comment by Heatmanofurioso** [comment]
Considering the library has been "abandoned/deprecated".
I suggest simply utilizing Angular's Meta components @matusbielik

**Comment by aaa123eee** [comment]
Yeah, now it's better to use `@angular/platform-browser`

**Comment by matusbielik** [comment]
@aaa123eee @Heatmanofurioso this library uses meta service from @angular/platform-browser under the hood, so I wouldn't say that using Meta service is 'better' per se.
@ngx-meta has a few usable capabilities that we find valuable, like MetaGuard, this way we can set title and meta tags in routes file.

As this library seems to be abandoned and the author doesn't even bother to answer questions about its future (but is still active on github in private repos), I decided to get rid of all the ngx-* libraries and implement the functionality myself.

**Comment by Heatmanofurioso** [comment]
@matusbielik You are correct, although I think Angular's Meta allows you to do that too by itself nowadays.
My main reason to drop the library is really how it seems to have been abandoned too.

It's a pity, as it really is a good project

**Comment by yangjunfocus** [comment]
I'm facing the same issue, any info on this?

**Comment by Volen99** [comment]
Same issue here :(

**Comment by Volen99** [comment]
Guys!! Peertube have been using ngx-meta, but now that it is no longer supported, they have deleted it and made their own guard here: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/core/routing/meta-guard.service.ts
and use it like this, e.g. 

    path: 'about',
    loadChildren: () => import('./+about/about.module').then(m => m.AboutModule),
    canActivateChild: [ MetaGuard ]

link: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/app-routing.module.ts

**Comment by fulls1z3** [comment]
need help with these PR's, especially with ng-packagr is failing. once done aim is first to ng 10 and then eventually to ng11 and ng12 (supporting all intermediate versions)
* https://github.com/fulls1z3/ngx-meta/pull/216
* https://github.com/fulls1z3/ngx-config/pull/169
* https://github.com/fulls1z3/ngx-cache/pull/141
* https://github.com/fulls1z3/ngx-auth/pull/135

and finally we're showcasing it on https://github.com/fulls1z3/universal/pull/755
