### ISSUE TITLE
Linked-In Social Share issue

### ISSUE THREAD

**Issue by sadiqueamt** [fulls1z3/ngx-meta#212]
Hi,
I have deployed my angular ssr app inside a folder.

Example. www.example.com/test/

And Og url is showing like this,  '/page_name'

so, facebook, twitter sharing is working fine, but linkedin taking og url as canonical URL. and it shows like www.example.com/page_name/ instead of www.example.com/test/page_name/

Any solution ?

**Comment by fulls1z3** [comment]
see  https://github.com/fulls1z3/universal
