### ISSUE TITLE
Uncaught TypeError: Cannot read property 'core' of undefined at ngx-meta-core.umd.js:4

### ISSUE THREAD

**Issue by playkang** [fulls1z3/ngx-meta#213]
**I'm submitting a ...**  (check one with "x")
```
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
```

**Current behavior**
![image](https://user-images.githubusercontent.com/70426256/111023090-5715e180-841a-11eb-96ff-c649aff460d4.png)

**Expected/desired behavior**

I added in angular.json
Because no use system.js
```
"scripts": [
              "node_modules/@ngx-meta/core/bundles/ngx-meta-core.umd.min.js"
            ]
```
Can I make this error go away?

**Environment**
* **Angular version:** 10.0.6

* **Browser:**
- [x] Chrome (desktop) version XX

**Comment by fulls1z3** [comment]
see https://github.com/fulls1z3/ngx-meta/pull/216
