### ISSUE TITLE
can't setTitle() from .component

### ISSUE THREAD

**Issue by ghost** [fulls1z3/ngx-meta#24]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

Only `setTag()` works on a component. `setTitle()` doesn't set any title, even if `true` is added as a second parameter. It simply ignores, and fallbacks to the default title set in `app.module`.

**Expected/desired behavior**

Being able to set the title from a component.

**Minimal reproduction of the problem with instructions**

Angular app is composed of a bootstrapping `app.module`, which is then divided in `pages.module` (composed of multiple blocks, ie: about-page), and `blocks.module` (composed of  multiple HTML elements, ie: slideshow-block).
Followed the README.md.

**Please tell us about your environment:**

* **Angular version:** 2.4.7

* **Browser:** [all]

 
* **Language:** [TypeScript 2.1.6]

* **Node (for AoT issues):** `node --version` =  7.4.0

**Comment by ghost** [comment]
Just realised there was the same issue on [vinaygopinath/ng2-meta issue #7](https://github.com/vinaygopinath/ng2-meta/issues/7). The trick is to use setTimeout as it follows:
```
setTimeout(() => {
  this.metaService.setTitle('test');
});
```
However, I don't fully understand what's happening. Is the setTitle() waiting for a request to end?
Should this behaviour be changed?

Sorry for any confusion.

**Comment by fulls1z3** [comment]
Hi @zM4J8ksETHCq, it's OK to open issues. Actually it's a great contribution to development of this utility.

However, this issue seems to be duplicate of #22, and I'm closing it. You can track current status on #22.

**Comment by rannaot** [comment]
Can you make a release with this issue solved?

**Comment by fulls1z3** [comment]
Hi @rannaot, I'd like to make it just now.

However, there're a lot of files needs to be reverted while `ngx-translate` integration is being completed. Within a few days I'll make the release.

**Comment by fulls1z3** [comment]
https://github.com/nglibs/meta/releases/tag/v0.2.0-rc.4
