### ISSUE TITLE
no refresh method in MetaService

### ISSUE THREAD

**Issue by stefan-krajnik** [fulls1z3/ngx-meta#47]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

I found `this.meta.refresh();` in readme. But there is no refresh method in MetaService delaration.

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by fulls1z3** [comment]
@stefan-krajnik there was a `refresh` method earlier, but it has been removed. Thanks for pointing this out, so that I'll remove it from README.
