### ISSUE TITLE
default meta not set

### ISSUE THREAD

**Issue by stefan-krajnik** [fulls1z3/ngx-meta#48]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
I've copied 
```
MetaModule.forRoot({
    provide: MetaLoader,
    useFactory: (metaFactory)
})
````

`metaFactory` function as well from readme.  Meta/title is not set, only if I change it via MetaService. Is it a bug or am I doing something wrong ?

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by fulls1z3** [comment]
@stefan-krajnik could you please post here your app.config and the component class where you use the `MetaService` - so that I can have a better look and suggest you what to do.
