### ISSUE TITLE
work with ngx-translate >= v7.x

### ISSUE THREAD

**Issue by chriseugenerodriguez** [fulls1z3/ngx-meta#49]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x ] feature request
```
The whole reason I want to use this if it works with ngx-translate, I use angular universal instead. I want to see if I can use dynamic translate in meta and title tags.

**Comment by fulls1z3** [comment]
@premiumwd in the beginning (*before including the callback method feature*) I was thinking about developing a custom loader which uses ngx-translate. Did you mean more or less such a feature?

Let me know about your ideas, and let's see what we can do.

**Comment by chriseugenerodriguez** [comment]
@fulls1z3 I have been working on this a couple of days, and a lot of people need this. I have found the issue with (ngx-translate + angular universal) and its with express engine setup on the server end when rendering the html views. If you make this work ngx-meta + ngx-translate you will completely take it over. I think for simplicity purposes, inheriting ngx-translate with ngx-meta would be preferred. So make it a feature of ngx-meta. :+1:

**Comment by fulls1z3** [comment]
@premiumwd thanks for the information, do you have any scratches (*code, design, etc*) for this feature? If so, please share them by uploading a ZIP file on this issue. If not, could you elaborate the required features with a little more details (*and sample cases if possible*) so that the feature would cover the exact needs.

**Comment by chriseugenerodriguez** [comment]
@fulls1z3 pretty self explanatory, I do not have code samples but basically, just have translate pipes with your ngx-meta from ngx-translate code.

**Comment by fulls1z3** [comment]
@premiumwd well, I will try to generate that use case on one of my projects and will ask you for further instructions. I think we can cover this feature, so step by step let's proceed 👍

**Comment by fulls1z3** [comment]
@premiumwd just to make sure, are we talking about **ngx-translate** `v7.x`?

**Comment by fulls1z3** [comment]
done
