### ISSUE TITLE
no exported member meta when aot compiler

### ISSUE THREAD

**Issue by OdaiTu** [fulls1z3/ngx-meta#50]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

when im making aot compiler using angular-cli this error comes up
ERROR in F:/zeina/rb2000_angular/rb2000/node_modules/@ngx-meta/core/src/meta.service.d.ts (1,10): Module '"F:/zeina/rb2000_angular/rb2000/node_modules/@angular/platform-browser/index"' has no export
ed member 'Meta'.

im using angular 2 v 2.4.10

so how can i solve this problem ?

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by fulls1z3** [comment]
@OdaiTu could you please tell me which version of `ngx-meta/core` did you use on your project (*v0.2.0 or v0.4.0*)? I think you should better have a look at `package.json` in `node_modules` and let me know about the exact version number.
