### ISSUE TITLE
include host/domain in "og:url"

### ISSUE THREAD

**Issue by nicky-lenaers** [fulls1z3/ngx-meta#51]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

When changing route to e.g. `/about-us`, only the path of the url is added to the meta: `<meta property="og:url" content="/about-us">`.

**Expected/desired behavior**

The full URL host should be in the `og:url` fragment, like so: `<meta property="og:url" content="https://company.com/about-us">`.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Incorrect Open Graph values in meta tags.

**Please tell us about your environment:**

Windows, NGINX

* **Angular version:** 2.0.X

4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   7.10

**Comment by fulls1z3** [comment]
@nicky-lenaers you should set to `applicationUrl` property using the `MetaLoader` in your app.config, this way the host/domain url will be preprended to `og:url`.
