### ISSUE TITLE
able to see the title and meta description in inspect but not in view source

### ISSUE THREAD

**Issue by jinnabaalu** [fulls1z3/ngx-meta#52]
Inspect view of the application

![image](https://user-images.githubusercontent.com/11784253/28720126-e0b0276c-73c9-11e7-8fe8-62c3ba6efd88.png)

View page source of the application

![image](https://user-images.githubusercontent.com/11784253/28720015-970f7130-73c9-11e7-8f09-114c3cfc9c82.png)

**Comment by fulls1z3** [comment]
@JinnaBalu this is normal, you'll need to implement server-side rendering to view the meta information on the page source. Please have a look at [ng-seed/universal](https://github.com/ng-seed/universal) for the proper implementation.
