### ISSUE TITLE
add `getTitle` method to `meta.service`

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/ngx-meta#54]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**
There's no interface which allows to retrieve the current page title using `meta.service`.

**Expected/desired behavior**
`metaService.getTitle` method should be introduced, and should return the current page title:
- [ ] with callback
- [ ] without callback

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
The page title needs to be used on different parts of the corresponding page. There're such scenarios where we need to supply this value to `ngrx`, etc.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by vlados** [comment]
Can we bump this with higher priority?

**Comment by fulls1z3** [comment]
@vlados i need that functionality, but had to delay it many times 😄 

what's your use case my friend?

**Comment by vlados** [comment]
@fulls1z3 Scenario: 
I have two components - 
ViewBuildings with url 'view/:id' and title added after loading the data for the corresponding id
ListBuildings with url 'list' with title List buildings
I also have ModalComponent that is loading ViewBuildings inside of  modal dialog which on open is changing the title. This is ok, but I need to add functionality on close to set the title for the original, before the open.

**Comment by vlados** [comment]
What if I add:

import { Title } from 'angular/platform-browser';
this.title.getTitle()

**Comment by stewones** [comment]
needing this too, would be awesome to have.

**Comment by logan-jobzmall** [comment]
Another use case: I have a title component that sits at the top of the mobile version of my site. I have the translation service that sets the title dynamically. Would be nice to able to display that value on this component. I guess I will need to find another way. 

EDIT: I am now just using `this.meta['title'].getTitle()`
