### ISSUE TITLE
cannot make it working

### ISSUE THREAD

**Issue by baucez** [fulls1z3/ngx-meta#59]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ x] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Minimal reproduction of the problem with instructions**

I followed the installation guide but i get this error:
Call to Node module failed with error: Prerendering failed because of error: [...]\node_modules\@angular\platform-browser\src\dom\dom_adapter.js:12
export function getDOM() {
^^^^^^
SyntaxError: Unexpected token export

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** [Chrome XX]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   6.11.1

**Comment by fulls1z3** [comment]
@baucez I think we're talking about angular 2.4.x, I'll need to have a look at its behavior. Some updates on deps sometimes cause this.

**Comment by fulls1z3** [comment]
@baucez I know it's pretty late, but I'm getting more or less similar errors with the new testing platform (*jest*). I'd like to hear about your tsconfig.json first, and see what we can do.
