### ISSUE TITLE
please add detailed install on readme

### ISSUE THREAD

**Issue by stewones** [fulls1z3/ngx-meta#60]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```

**Current behavior**

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** X.Y.Z

* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: XX  
- Platform:  

* Others:

**Comment by fulls1z3** [comment]
@stewwan can you please elaborate more details? what installation steps you actually need?

**Comment by stewones** [comment]
@fulls1z3  just cant figure out what package to use,  ngx-meta or ngx-meta/core or both. 
thx for fast reply

**Comment by fulls1z3** [comment]
@stewwan the project's name is `ngx-meta` and the npm package's name is `@ngx-meta/core`. If you check the README file, you'll notice a table enumerating the packages under the scope of `ngx-meta`. This table contains both links to the package's README as well as npm package's link.

The answer to your question, you need to include `@ngx-meta/core` right at your `package.json`.

Happy coding 👍

**Comment by stewones** [comment]
ok thx @fulls1z3 . but just to known, if you wanna improve your package.

cant figure out how it works. I miss a simple sample, your examples are a bit advanced. I just need to put a title in the routes

I did this steps and it doesn't works

1 - `npm install @ngx-meta/core --save`

2 - 
```js
imports: [
    BrowserModule,
    RoutingModule,
    MetaModule.forRoot(),
]
```

3 -
```js
const routes: Routes = [
    // home
    {
        path: '',
        component: HomePageComponent,
        data: {
            meta: {
                title: 'Sweet home',
                override: true,
                description: 'Home, home sweet home... and what?'
            }
        }
    },
```

**Comment by stewones** [comment]
ok it was my fault. just realized I missed the MetaGuard step in routes. Anyway thanks.

**Comment by fulls1z3** [comment]
@stewwan you're welcome, and if you think there might be improvements (*in terms of making the things easier*), feel free to create a **pull request**.
