### ISSUE TITLE
combine with ng2-translate

### ISSUE THREAD

**Issue by aegyed91** [fulls1z3/ngx-meta#7]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[x] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

Hi, I want to combine ng2-metadata with [ng2-translate](https://github.com/ocombe/ng2-translate). Their [TranslateService](https://github.com/ocombe/ng2-translate#translateservice)`#get(key: string|Array<string>, interpolateParams?: Object): Observable<string|Object>` is async. What i came up with is a `MetadataResole` class that looks like this:

```ts
@Injectable()
export class MetadataResolve implements Resolve<any> {
  constructor(private translate: TranslateService, private metadataService: MetadataService) {
  }

  resolve(route: ActivatedRouteSnapshot) {
    return this.translate.get((route.data as any).m3tadata.title).toPromise().then(v => {
      this.metadataService.setTitle(v);
    });
  }
}
```

and is being used like this:

```ts
  {
    path: 'signup',
    component: SignupC,
    canActivate: [LoggedOutG],
    data: {m3tadata: {title: 'AUTH.SIGNUP_P.TITLE'}},
    resolve: {metadata: MetadataResolve}
  },
```

Now, this is working. But it looks ugly, do u know of any better way? @fulls1z3

**Comment by fulls1z3** [comment]
Hi @tsm91.

Actually combining ng2-metadata with ng2-translate is already in the roadmap, and soon will PR the results on [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced/) repository.

However we're currently working on upgrading to angular 2.4.x, fixing other dependencies and testing the upgrade.

I think I can provide a more elegant way and soon share the results. Stay tuned.

**Comment by aegyed91** [comment]
Cool! Thx for the fast reply, will keep an eye on this project.

**Comment by Chuvisco88** [comment]
Any updates on this?

**Comment by fulls1z3** [comment]
Hi @Chuvisco88, working on a localized-router which supports lazy-loaded route names to be translated. After this, i'm going to move all libraries (ng2-config, ng2-metadata, ng2-webapi, ng2-auth and ng2-localized-router) under @nglibs scope on npm.

In the meantime, I'm working on a quickstart package which includes all @nglibs utilities and demonstrates their usage.

Stay tuned, lots of more is coming :)

**Comment by Chuvisco88** [comment]
@fulls1z3 you might look into https://github.com/meeroslav/localize-router as this is already a solution for localized routing. Might help :)

**Comment by fulls1z3** [comment]
@Chuvisco88 I used it already, however it doesn't work with lazy-loaded routes (as discussed on [#3](https://github.com/Greentube/localize-router/issues/3)).

**Comment by Chuvisco88** [comment]
@fulls1z3 I replaced ng2-meta with this repo for now. Really looking forward to translated meta tags. Keep it up 👍

**Comment by fulls1z3** [comment]
Hi @Chuvisco88, I'm currently working on fixes with [@nglibs/i18n-router](https://github.com/nglibs/i18n-router) (angular-cli capabilities). Soon, a loader (probably named as `MetadataTranslateLoader` will be published.

**Comment by fulls1z3** [comment]
Hi @tsm91, @Chuvisco88.

I know it's been quite long time, but I've been busy with other projects as well as resolving issues with higher priority. I've succeeded developing a loader which uses the `TranslateService` and refactoring @nglibs/meta to use observables.

Currently writing unit tests. I think within a day or two, this feature will be OK and included by rc.4.

**Comment by fulls1z3** [comment]
Finally committed the changes. Some more tasks with instructions and gonna be released asap.

**Comment by fulls1z3** [comment]
Released, you can install it via npm. Also, check the documentation and [@nglibs/example-app](https://github.com/nglibs/example-app) for in-depth examples.
