### ISSUE TITLE
compile errors when using AOT compiling with ng2-metadata

### ISSUE THREAD

**Issue by JochemKuijpers** [fulls1z3/ngx-meta#8]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
I currently using the module as follows:

	import {NgModule} from '@angular/core';
	//...
	import {AppRoutes} from './app.routes';
	import {MetadataModule} from 'ng2-metadata';

	@NgModule({
	    declarations: [
	//...
	    ],
	    imports: [
	//...
		RouterModule.forRoot(AppRoutes),
		MetadataModule.forRoot()
	//...
	    ],
	    bootstrap: [AppComponent]
	})
	export class AppModule {
	}

My AppRoutes contains metadata and works like a charm with JIT compilation, so I don't believe it to be faulty.

I also pass the service into AppComponent for dependency injection:

	//...
	constructor(private metadataService: MetadataService) {}
	//...

**Expected/desired behavior**
Running the Angular CLI tool with the --aot parameter, should compile the app into an ahead-of-time compiled package, but instead it throws an error for the ng2-metadata package.

**Minimal reproduction of the problem with instructions**
Here's a repository set up with the angular-cli tool (`ng new derp`), substituting my current dependencies and tsconfig and adding the `ng2-metadata` code to the app module and app component.

https://github.com/JochemKuijpers/derp

Then run the `ng build --aot` command. This will fail even though JIT works without any problems.

The errors I'm seeing are:

	WARNING in ./src/app/app.module.ngfactory.ts
	335:44 export 'metadataLoaderFactory' (imported as 'import1') was not found in './app.module'

	ERROR in ./src/app/app.module.ngfactory.ts
	Module not found: Error: Can't resolve '../metadata.service' in '/home/jochem/repos/derp/src/app'
	 @ ./src/app/app.module.ngfactory.ts 52:0-48
	 @ ./src/main.ts
	 @ multi main

**What is the motivation / use case for changing the behavior?**
I like to use ng2-metadata with my project but currently I cannot use it in my deployment (with AOT compiling)

**Please tell us about your environment:**
Ubuntu 16.04 LTS 64-bit

* **Angular version:** 2.2.3

I currently cannot upgrade to any newer version in my current project, so if the problem cannot be fixed in this Angular version, I may be forced to drop `ng2-metadata`.

* **Browser:** all

 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` = v7.3.0, `npm --version` = 3.10.10

**Comment by fulls1z3** [comment]
Hi @JochemKuijpers,

First of all I'd like to thank you for all the detailed information above, and also for accelerating testing of **ng2-metadata**: I was actually planning to test it nowadays using the latest **angular (2.4.1)** at the moment - so you gave me a chance for it :)

I cloned your repo **derp**, performed an `npm install`, ran `ng build --aot`, and I also got some compile errors, similar to yours:

```
ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-metadata relative to C:/Users/fulls1z3/Source/Repos/derp/src/app/app.module.ts., resolving symbol AppModule in C:/Users/fulls1z3/Source/Repos/derp/src/app/app.module.ts, resolving symbol AppModule in C:/Users/fulls1z3/Source/Repos/derp/src/app/app.module.ts, resolving symbol AppModule in C:/Users/fulls1z3/Source/Repos/derp/src/app/app.module.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\fulls1z3\Source\Repos\derp\src'
 @ ./src/main.ts 4:0-74
 @ multi main

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve 'C:\Users\fulls1z3\Source\Repos\derp\src\$$_gendir' in 'C:\Users\fulls1z3\Source\Repos\derp\node_modules\@angular\core\src\linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main
```

Then, I created a new ng project (using `ng new derp2`) using the latest **angular-cli (1.0.0-beta.24)** at the moment, and tested **ng2-metadata**. Results were good, I observed that aot build succeeded without errors:

```
C:\Users\fulls1z3\Source\Repos\derp2>ng build --aot
Hash: 12080e0862bf80ecb0ce
Time: 28073ms
chunk    {0} main.bundle.js, main.bundle.map (main) 33.3 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.77 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 1.7 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

Then I cleaned the `node_modules` dir of solution **derp**, fixed the dependencies according to **derp2** and ran `ng build --aot` on **derp** and it failed again.

For that reason, I suggest you to have a look at the attached solution which has been built using the latest **angular-cli** and **angular** components, and let me know about the status.

Hope we will succeed with it!

[derp2.zip](https://github.com/fulls1z3/ng2-metadata/files/671239/derp2.zip)

**Comment by JochemKuijpers** [comment]
I've adapted my project and copied the versions from the `package.json` in your zip archive. This indeed fixes the compiling error. Thanks, my issue is now resolved.

**Comment by slegaitis** [comment]
I'm having same issue with Angular 4.4.4 and ng2-metadata 2.0.1 :( With Aot compiler too.

Any ideas?

**Comment by fulls1z3** [comment]
@tauciokas as seen as on [npm](https://www.npmjs.com/package/ng2-metadata) ng2-metadata is no longer supported and has been deprecated. Please use the [@ngx-meta/core package](https://www.npmjs.com/package/@ngx-meta/core) instead.
